"use client";

import { useEffect, useMemo, useState } from "react";
import { formatMoney, rooms, services } from "../../lib/site-data";

type Booking = { code:string; guest_name:string; phone:string; email:string; room_name:string; room_slug:string; check_in:string; check_out:string; adults:number; children:number; total:number; prepayment:number; status:string; created_at:string; source:string; internal_note?:string };
const demos:Booking[]=[
  {code:"LB-260819-A4X2M",guest_name:"Анна Коваленко",phone:"+38 (067) 442-18-07",email:"anna@example.com",room_name:"Шале «Тихое озеро»",room_slug:"tikhoe-ozero",check_in:"2026-08-21",check_out:"2026-08-24",adults:2,children:2,total:22900,prepayment:11450,status:"confirmed",created_at:"2026-08-15 12:42",source:"Сайт"},
  {code:"LB-260820-K7P9Q",guest_name:"Игорь Мельник",phone:"+38 (093) 217-50-41",email:"igor@example.com",room_name:"Домик «Сосновый»",room_slug:"sosnovyi",check_in:"2026-08-23",check_out:"2026-08-25",adults:2,children:0,total:9800,prepayment:0,status:"pending",created_at:"2026-08-17 09:16",source:"Сайт"},
  {code:"LB-260821-L3R6S",guest_name:"Елена Бойко",phone:"+38 (050) 735-11-28",email:"elena@example.com",room_name:"Вилла с бассейном",room_slug:"villa-pool",check_in:"2026-08-26",check_out:"2026-08-29",adults:5,children:1,total:37250,prepayment:18500,status:"prepaid",created_at:"2026-08-16 18:03",source:"Телефон"},
  {code:"LB-260822-D8W1T",guest_name:"Сергей Литвин",phone:"+38 (097) 181-40-60",email:"sergey@example.com",room_name:"Студия «Панорама»",room_slug:"panorama",check_in:"2026-08-18",check_out:"2026-08-20",adults:2,children:0,total:7200,prepayment:7200,status:"checked_in",created_at:"2026-08-12 14:55",source:"Instagram"},
  {code:"LB-260823-B2N5V",guest_name:"Оксана Романюк",phone:"+38 (066) 518-73-22",email:"oksana@example.com",room_name:"Коттедж «Дубовый»",room_slug:"dubovyi",check_in:"2026-08-30",check_out:"2026-09-01",adults:3,children:2,total:17400,prepayment:0,status:"cancelled",created_at:"2026-08-14 11:10",source:"Сайт"},
];
const statusLabels:Record<string,string>={new:"Новая заявка",pending:"Ожидает подтверждения",confirmed:"Подтверждена",prepaid:"Предоплата получена",paid:"Полностью оплачена",checked_in:"Гость заселён",completed:"Завершена",cancelled:"Отменена",no_show:"Неявка"};
const nav=[['dashboard','Обзор','⌂'],['bookings','Бронирования','▣'],['calendar','Календарь','□'],['rooms','Номера','⌑'],['services','Услуги','✦'],['content','Контент сайта','≡'],['settings','Настройки','⚙']];

export default function AdminDashboard({user}:{user:{displayName:string;email:string}}) {
  const [tab,setTab]=useState("dashboard"); const [bookings,setBookings]=useState<Booking[]>(demos); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<Booking|null>(null); const [notice,setNotice]=useState(""); const [roomRows,setRoomRows]=useState(rooms.map(r=>({...r,visible:true}))); const [serviceRows,setServiceRows]=useState(services.map(s=>({...s,visible:true}))); const [siteName,setSiteName]=useState("Лесной берег");
  useEffect(()=>{fetch('/api/bookings').then(r=>r.ok?r.json():null).then(j=>{if(j?.bookings?.length)setBookings([...j.bookings,...demos])}).catch(()=>{})},[]);
  const filtered=useMemo(()=>bookings.filter(b=>(status==="all"||b.status===status)&&(!query||`${b.code} ${b.guest_name} ${b.phone} ${b.room_name}`.toLowerCase().includes(query.toLowerCase()))),[bookings,status,query]);
  const revenue=bookings.filter(b=>!['cancelled','no_show'].includes(b.status)).reduce((s,b)=>s+b.total,0); const prepayments=bookings.reduce((s,b)=>s+(b.prepayment||0),0);
  const updateBooking=async(code:string,newStatus:string)=>{const old=bookings;setBookings(bookings.map(b=>b.code===code?{...b,status:newStatus}:b));try{const res=await fetch('/api/bookings',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({code,status:newStatus,prepayment:selected?.prepayment||0,internalNote:selected?.internal_note||''})});if(!res.ok)throw new Error();setNotice('Изменения сохранены');setTimeout(()=>setNotice(''),2500)}catch{setBookings(old);setNotice('Не удалось сохранить изменение')}};
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="admin-logo" href="/"><span>ЛБ</span><b>{siteName}<small>управление комплексом</small></b></a><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i>{icon}</i>{label}{id==='bookings'&&<em>{bookings.filter(b=>b.status==='pending').length}</em>}</button>)}</nav><div className="admin-user"><span>{user.displayName.slice(0,2).toUpperCase()}</span><b>{user.displayName}<small>{user.email}</small></b><a href="/signout-with-chatgpt?return_to=/">↗</a></div></aside><main className="admin-main"><header className="admin-top"><div><small>Административная панель</small><h1>{{dashboard:'Добрый день!',bookings:'Бронирования',calendar:'Календарь загрузки',rooms:'Номера и домики',services:'Услуги',content:'Контент сайта',settings:'Настройки'}[tab]}</h1></div><div><a className="admin-view" href="/" target="_blank">Посмотреть сайт ↗</a><button className="admin-primary" onClick={()=>{setTab('bookings');setSelected({code:'Новая заявка',guest_name:'',phone:'',email:'',room_name:rooms[0].name,room_slug:rooms[0].slug,check_in:'',check_out:'',adults:2,children:0,total:0,prepayment:0,status:'pending',created_at:'',source:'Администратор'})}}>+ Новое бронирование</button></div></header>{notice&&<div className="admin-notice">{notice}</div>}

  {tab==='dashboard'&&<><section className="metric-grid"><article><span>Новые заявки<small>за последние 7 дней</small></span><strong>{bookings.filter(b=>b.status==='pending').length}</strong><em>требуют внимания</em></article><article><span>Загрузка сегодня<small>4 из 6 домиков</small></span><strong>67%</strong><em className="good">+12% к прошлой неделе</em></article><article><span>Выручка<small>август 2026</small></span><strong>{formatMoney(revenue)}</strong><em className="good">Предоплат: {formatMoney(prepayments)}</em></article><article><span>Средний чек<small>за проживание</small></span><strong>{formatMoney(Math.round(revenue/bookings.length))}</strong><em>+ услуги в среднем 2 180 ₴</em></article></section><section className="admin-grid-two"><div className="admin-panel"><div className="panel-head"><div><h2>Ближайшие заезды</h2><span>Следующие 7 дней</span></div><button onClick={()=>setTab('bookings')}>Все бронирования →</button></div><div className="arrival-list">{bookings.filter(b=>b.status!=='cancelled').slice(0,4).map((b,i)=><button onClick={()=>{setSelected(b);setTab('bookings')}} key={b.code}><span className="date-box"><b>{b.check_in.slice(-2)}</b><small>авг</small></span><span><strong>{b.guest_name}</strong><small>{b.room_name} · {b.adults+b.children} гостя</small></span><em className={`status ${b.status}`}>{statusLabels[b.status]}</em><i>›</i></button>)}</div></div><div className="admin-panel occupancy"><div className="panel-head"><div><h2>Загрузка номеров</h2><span>Сегодня, 17 августа</span></div><b>4 / 6</b></div><div className="donut"><div><strong>67%</strong><span>занято</span></div></div><ul><li><i className="occupied"/>Занято <b>4</b></li><li><i className="free"/>Свободно <b>2</b></li><li><i className="blocked"/>Заблокировано <b>0</b></li></ul></div></section><section className="admin-grid-two lower"><div className="admin-panel"><div className="panel-head"><div><h2>Ближайшие выезды</h2><span>Сегодня и завтра</span></div></div><div className="checkout-list">{bookings.slice(0,3).map(b=><div key={b.code}><span>{b.check_out.slice(-2)}<small>авг</small></span><p><strong>{b.guest_name}</strong>{b.room_name}</p><b>до 11:00</b></div>)}</div></div><div className="admin-panel"><div className="panel-head"><div><h2>Популярные номера</h2><span>По бронированиям за месяц</span></div></div><div className="popular-list">{rooms.slice(0,3).map((r,i)=><div key={r.slug}><img src={r.image} alt=""/><span><strong>{r.name}</strong><small>{12-i*3} бронирований</small></span><b>{formatMoney(r.price)}</b></div>)}</div></div></section></>}

  {tab==='bookings'&&<section className="admin-panel bookings-panel"><div className="table-tools"><div className="admin-search"><span>⌕</span><input placeholder="Имя, телефон или номер заявки" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Все статусы</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button>Фильтры</button><span>Найдено: {filtered.length}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Заявка</th><th>Гость</th><th>Номер</th><th>Даты</th><th>Гости</th><th>Сумма</th><th>Статус</th><th></th></tr></thead><tbody>{filtered.map(b=><tr key={b.code} onClick={()=>setSelected(b)}><td><strong>{b.code}</strong><small>{b.created_at}</small></td><td><strong>{b.guest_name}</strong><small>{b.phone}</small></td><td>{b.room_name}</td><td><strong>{b.check_in}</strong><small>→ {b.check_out}</small></td><td>{b.adults+b.children}</td><td><strong>{formatMoney(b.total)}</strong><small>предоплата {formatMoney(b.prepayment||0)}</small></td><td><span className={`status ${b.status}`}>{statusLabels[b.status]}</span></td><td>›</td></tr>)}</tbody></table></div></section>}

  {tab==='calendar'&&<Calendar bookings={bookings}/>} 
  {tab==='rooms'&&<section className="admin-panel management-panel"><div className="management-head"><div><h2>Все варианты проживания</h2><p>{roomRows.length} объектов · {roomRows.filter(r=>r.visible).length} опубликовано</p></div><button className="admin-primary" onClick={()=>setNotice('Форма создания номера открыта в демонстрационном режиме')}>+ Добавить номер</button></div><div className="management-list">{roomRows.map((r,i)=><div key={r.slug}><span className="drag">⋮⋮</span><img src={r.image} alt=""/><span className="manage-title"><strong>{r.name}</strong><small>{r.type} · до {r.guests} гостей · {r.area} м²</small></span><b>{formatMoney(r.price)}<small>за ночь</small></b><label className="switch"><input type="checkbox" checked={r.visible} onChange={()=>setRoomRows(roomRows.map(x=>x.slug===r.slug?{...x,visible:!x.visible}:x))}/><span/></label><button onClick={()=>setNotice(`${r.name}: редактор открыт`)}>Редактировать</button><button onClick={()=>{setRoomRows([...roomRows,{...r,slug:r.slug+'-copy',name:r.name+' — копия'}]);setNotice('Номер продублирован')}}>⋯</button></div>)}</div></section>}
  {tab==='services'&&<section className="admin-panel management-panel"><div className="management-head"><div><h2>Дополнительные услуги</h2><p>{serviceRows.length} услуг в 7 категориях</p></div><button className="admin-primary" onClick={()=>setNotice('Форма новой услуги открыта')}>+ Добавить услугу</button></div><div className="management-list service-manage">{serviceRows.map(s=><div key={s.name}><img src={s.image} alt=""/><span className="manage-title"><strong>{s.name}</strong><small>{s.category} · {s.duration}</small></span><b>{formatMoney(s.price)}<small>{s.unit}</small></b>{s.booking&&<em>По записи</em>}<label className="switch"><input type="checkbox" checked={s.visible} onChange={()=>setServiceRows(serviceRows.map(x=>x.name===s.name?{...x,visible:!x.visible}:x))}/><span/></label><button onClick={()=>setNotice(`${s.name}: изменения сохранены`)}>Редактировать</button></div>)}</div></section>}
  {tab==='content'&&<section className="content-admin"><div className="admin-panel content-nav"><h2>Разделы сайта</h2>{['Главная страница','Контакты и карта','Преимущества','Отзывы','Галерея','Правила пребывания','Политики и документы'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}<span>›</span></button>)}</div><div className="admin-panel content-editor"><div className="panel-head"><div><h2>Главная страница</h2><span>Основные тексты и призывы</span></div><button className="admin-primary" onClick={()=>setNotice('Контент сохранён')}>Сохранить</button></div><label><span>Название комплекса</span><input value={siteName} onChange={e=>setSiteName(e.target.value)}/></label><label><span>Заголовок первого экрана</span><input defaultValue="Место, где становится тихо"/></label><label><span>Короткое описание</span><textarea rows={4} defaultValue="Уютные домики у воды, тёплый бассейн и SPA — всё, чтобы замедлиться и снова услышать себя."/></label><div className="editor-photo"><img src={rooms[3].image} alt=""/><span><strong>Главное изображение</strong><small>Рекомендуемый размер 2200 × 1400 px</small></span><button>Заменить фото</button></div></div></section>}
  {tab==='settings'&&<section className="settings-grid"><div className="admin-panel"><h2>Основные настройки</h2><label><span>Название комплекса</span><input value={siteName} onChange={e=>setSiteName(e.target.value)}/></label><label><span>Телефон</span><input defaultValue="+38 (067) 123-45-67"/></label><label><span>Email</span><input defaultValue="hello@lisnyi-bereg.ua"/></label><label><span>Адрес</span><input defaultValue="Киевская область, с. Лесное, ул. Озёрная, 12"/></label><button className="admin-primary" onClick={()=>setNotice('Настройки сохранены')}>Сохранить настройки</button></div><div className="admin-panel"><h2>Доступ и безопасность</h2><p>Административная панель защищена входом. Все изменения записываются в журнал действий.</p><div className="admin-person"><span>{user.displayName.slice(0,2).toUpperCase()}</span><b>{user.displayName}<small>{user.email} · Владелец</small></b><em>Активен</em></div><button>Добавить администратора</button></div></section>}
  </main>{selected&&<BookingDrawer booking={selected} onClose={()=>setSelected(null)} onUpdate={updateBooking}/>}</div>;
}

function Calendar({bookings}:{bookings:Booking[]}) { const days=Array.from({length:14},(_,i)=>new Date(2026,7,17+i)); return <section className="admin-panel calendar-panel"><div className="calendar-tools"><div><button>‹</button><h2>17–30 августа 2026</h2><button>›</button></div><div><button>День</button><button className="active">2 недели</button><button>Месяц</button></div><button>Сегодня</button></div><div className="calendar-scroll"><div className="calendar-grid"><div className="calendar-corner">Номер</div>{days.map(d=><div className="calendar-day" key={d.toISOString()}><small>{['вс','пн','вт','ср','чт','пт','сб'][d.getDay()]}</small><b>{d.getDate()}</b></div>)}{rooms.map((r,ri)=><div className="calendar-row" style={{gridRow:ri+2}} key={r.slug}><div className="calendar-room"><img src={r.image} alt=""/><span>{r.name}<small>{formatMoney(r.price)}</small></span></div>{days.map(d=><div className="day-cell" key={d.toISOString()}/>) }{bookings.filter(b=>b.room_slug===r.slug&&!['cancelled'].includes(b.status)).map((b,i)=>{const start=Math.max(0,Math.round((new Date(b.check_in).getTime()-new Date(2026,7,17).getTime())/86400000));const len=Math.max(1,Math.round((new Date(b.check_out).getTime()-new Date(b.check_in).getTime())/86400000));return <div className={`booking-bar ${b.status}`} style={{left:`calc(190px + ${start} * 74px + 4px)`,width:`calc(${len} * 74px - 8px)`,top:'17px'}} key={b.code}><b>{b.guest_name}</b><span>{b.adults+b.children} гостя</span></div>})}</div>)}</div></div><div className="calendar-legend">{Object.entries(statusLabels).slice(1,6).map(([k,v])=><span key={k}><i className={k}/>{v}</span>)}</div></section> }

function BookingDrawer({booking,onClose,onUpdate}:{booking:Booking;onClose:()=>void;onUpdate:(c:string,s:string)=>void}) { const [s,setS]=useState(booking.status); return <div className="drawer-shade" onClick={onClose}><aside className="booking-drawer" onClick={e=>e.stopPropagation()}><header><div><small>Бронирование</small><h2>{booking.code}</h2></div><button onClick={onClose}>×</button></header><div className="drawer-body"><label><span>Статус</span><select value={s} onChange={e=>setS(e.target.value)}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><section><h3>Гость</h3><p><strong>{booking.guest_name||'Новый гость'}</strong>{booking.phone}<br/>{booking.email}</p></section><section><h3>Проживание</h3><p><strong>{booking.room_name}</strong>{booking.check_in||'Дата'} → {booking.check_out||'Дата'}<br/>{booking.adults} взрослых · {booking.children} детей</p></section><section className="drawer-money"><div><span>Стоимость</span><strong>{formatMoney(booking.total)}</strong></div><div><span>Предоплата</span><strong>{formatMoney(booking.prepayment)}</strong></div><div><span>Остаток</span><strong>{formatMoney(booking.total-booking.prepayment)}</strong></div></section><label><span>Внутренняя заметка</span><textarea rows={4} defaultValue={booking.internal_note} placeholder="Видно только сотрудникам"/></label><small className="source">Источник: {booking.source} · Создано {booking.created_at}</small></div><footer><button onClick={onClose}>Отмена</button><button className="admin-primary" onClick={()=>{onUpdate(booking.code,s);onClose()}}>Сохранить изменения</button></footer></aside></div> }
