import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const adminUsers = sqliteTable("admin_users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  externalId: text("external_id").notNull(),
  email: text("email").notNull(),
  name: text("name"),
  role: text("role").notNull().default("manager"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, t => [uniqueIndex("idx_admin_users_external_id").on(t.externalId), uniqueIndex("idx_admin_users_email").on(t.email)]);

export const roomTypes = sqliteTable("room_types", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), slug: text("slug").notNull().unique() });
export const roomsTable = sqliteTable("rooms", {
  id: integer("id").primaryKey({ autoIncrement: true }), slug: text("slug").notNull().unique(), name: text("name").notNull(), roomTypeId: integer("room_type_id").references(() => roomTypes.id), summary: text("summary").notNull(), description: text("description").notNull(), price: integer("price").notNull(), oldPrice: integer("old_price"), capacity: integer("capacity").notNull(), area: real("area").notNull(), beds: text("beds").notNull(), bedrooms: integer("bedrooms").notNull(), visible: integer("visible", {mode:"boolean"}).notNull().default(true), popular: integer("popular", {mode:"boolean"}).notNull().default(false), sortOrder: integer("sort_order").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, t => [index("idx_rooms_visible_sort").on(t.visible, t.sortOrder)]);
export const amenities = sqliteTable("amenities", { id: integer("id").primaryKey({autoIncrement:true}), name: text("name").notNull().unique(), icon: text("icon") });
export const roomAmenities = sqliteTable("room_amenities", { roomId: integer("room_id").notNull().references(()=>roomsTable.id), amenityId: integer("amenity_id").notNull().references(()=>amenities.id) }, t => [uniqueIndex("idx_room_amenity_unique").on(t.roomId,t.amenityId)]);
export const roomPhotos = sqliteTable("room_photos", { id: integer("id").primaryKey({autoIncrement:true}), roomId: integer("room_id").notNull().references(()=>roomsTable.id), storageKey: text("storage_key"), url: text("url").notNull(), alt: text("alt").notNull().default(""), isMain: integer("is_main",{mode:"boolean"}).notNull().default(false), sortOrder: integer("sort_order").notNull().default(0) }, t=>[index("idx_room_photos_room_sort").on(t.roomId,t.sortOrder)]);

export const serviceCategories = sqliteTable("service_categories", { id: integer("id").primaryKey({autoIncrement:true}), name: text("name").notNull(), slug: text("slug").notNull().unique(), sortOrder: integer("sort_order").notNull().default(0) });
export const servicesTable = sqliteTable("services", { id: integer("id").primaryKey({autoIncrement:true}), categoryId: integer("category_id").references(()=>serviceCategories.id), name: text("name").notNull(), description: text("description").notNull(), price: integer("price").notNull(), unit: text("unit").notNull(), duration: text("duration"), imageUrl: text("image_url"), storageKey: text("storage_key"), requiresBooking: integer("requires_booking",{mode:"boolean"}).notNull().default(false), bookable: integer("bookable",{mode:"boolean"}).notNull().default(true), visible: integer("visible",{mode:"boolean"}).notNull().default(true), sortOrder: integer("sort_order").notNull().default(0) });
export const guests = sqliteTable("guests", { id: integer("id").primaryKey({autoIncrement:true}), name: text("name").notNull(), phone: text("phone").notNull(), email: text("email").notNull(), notes: text("notes"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_guests_phone").on(t.phone),index("idx_guests_email").on(t.email)]);
export const bookings = sqliteTable("bookings", { id: integer("id").primaryKey({autoIncrement:true}), code: text("code").notNull().unique(), guestId: integer("guest_id").references(()=>guests.id), roomSlug: text("room_slug").notNull(), roomName: text("room_name").notNull(), checkIn: text("check_in").notNull(), checkOut: text("check_out").notNull(), adults: integer("adults").notNull(), children: integer("children").notNull().default(0), childAges: text("child_ages"), guestName: text("guest_name").notNull(), phone: text("phone").notNull(), email: text("email").notNull(), comment: text("comment"), internalNote: text("internal_note"), source: text("source").notNull().default("site"), status: text("status").notNull().default("pending"), total: integer("total").notNull(), prepayment: integer("prepayment").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_bookings_room_dates").on(t.roomSlug,t.checkIn,t.checkOut), index("idx_bookings_status_checkin").on(t.status,t.checkIn), index("idx_bookings_created").on(t.createdAt)]);
export const bookingNights = sqliteTable("booking_nights", { id: integer("id").primaryKey({autoIncrement:true}), bookingCode: text("booking_code").notNull(), roomSlug: text("room_slug").notNull(), night: text("night").notNull() }, t=>[uniqueIndex("idx_booking_nights_unique").on(t.roomSlug,t.night), index("idx_booking_nights_code").on(t.bookingCode)]);
export const bookingServices = sqliteTable("booking_services", { id: integer("id").primaryKey({autoIncrement:true}), bookingId: integer("booking_id").references(()=>bookings.id), bookingCode: text("booking_code").notNull(), serviceId: integer("service_id").references(()=>servicesTable.id), serviceName: text("service_name").notNull(), price: integer("price").notNull(), quantity: integer("quantity").notNull().default(1) }, t=>[index("idx_booking_services_booking").on(t.bookingId),index("idx_booking_services_code").on(t.bookingCode)]);
export const payments = sqliteTable("payments", { id: integer("id").primaryKey({autoIncrement:true}), bookingId: integer("booking_id").notNull().references(()=>bookings.id), amount: integer("amount").notNull(), kind: text("kind").notNull().default("prepayment"), method: text("method"), status: text("status").notNull().default("received"), note: text("note"), paidAt: text("paid_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_payments_booking").on(t.bookingId)]);
export const blockedDates = sqliteTable("blocked_dates", { id: integer("id").primaryKey({autoIncrement:true}), roomSlug: text("room_slug").notNull(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), reason: text("reason"), createdBy: text("created_by"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_blocked_dates_room_dates").on(t.roomSlug,t.startDate,t.endDate)]);

export const reviews = sqliteTable("reviews", { id: integer("id").primaryKey({autoIncrement:true}), guestName: text("guest_name").notNull(), text: text("text").notNull(), rating: integer("rating").notNull(), stayLabel: text("stay_label"), visible: integer("visible",{mode:"boolean"}).notNull().default(true), sortOrder: integer("sort_order").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const galleryPhotos = sqliteTable("gallery_photos", { id: integer("id").primaryKey({autoIncrement:true}), category: text("category").notNull(), url: text("url").notNull(), storageKey: text("storage_key"), alt: text("alt").notNull().default(""), visible: integer("visible",{mode:"boolean"}).notNull().default(true), sortOrder: integer("sort_order").notNull().default(0) });
export const siteSettings = sqliteTable("site_settings", { key: text("key").primaryKey(), value: text("value").notNull(), type: text("type").notNull().default("text"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedBy: text("updated_by") });
export const contentPages = sqliteTable("content_pages", { id: integer("id").primaryKey({autoIncrement:true}), slug: text("slug").notNull().unique(), title: text("title").notNull(), content: text("content").notNull(), kind: text("kind").notNull().default("page"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedBy: text("updated_by") });
export const auditLog = sqliteTable("audit_log", { id: integer("id").primaryKey({autoIncrement:true}), actorId: text("actor_id").notNull(), actorEmail: text("actor_email").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), details: text("details"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, t=>[index("idx_audit_log_created").on(t.createdAt)]);
